### ISSUE TITLE
Discord update broke urgent color

### ISSUE THREAD

**Issue by aidenmadaffri** [guglicap/wal-discord#11]
The latest Discord update seems to have broken the $colorUrgent. My urgent color is #81abd9 and appears in the css generated yet does not appear in the client. Other colors do not seem to work either. Neither BetterDiscord or BeautifulDiscord work.

**Comment by ghost** [comment]
I'm experiencing this problem as well

**Comment by guglicap** [comment]
Thanks for the report. I'm a little busy right now so I can't fix it right away. If anyone finds a way to solve it, PRs are always welcome.

**Comment by cprn** [comment]
I can fix it but I don't know how it looked before so I need a screenshot or a better description. Either that or you can go to any server in your browser on https://discordapp.com, right click whatever is supposed to be painted and select "Inspect element", then go up the DOM tree until you find the correct class witch CSS colour on it and paste it here.

**Comment by guglicap** [comment]
![image](https://user-images.githubusercontent.com/17258072/79843199-3be15400-83ba-11ea-90e7-c4783c4c7b2b.png)

been trying to work on this but the inspection tool turns into a blueish rectangle as soon as it turns up, does anyone know how to solve it or have the same issue?

**Comment by cprn** [comment]
Well, nope. Maybe when you turn on the developer mode in options? I don't know much about electron. I checked class names on discordapp.com last time I sent a PR.

**Comment by guglicap** [comment]
Nope, I do have developer mode turned on. Can't seem to find a way to fix it, I guess I'll wait for a discord update or something.
