### ISSUE TITLE
new chat / friend update broke the background colors (and the part around the settings/pf)

### ISSUE THREAD

**Issue by jrvgr** [guglicap/wal-discord#15]
titel says it all

**Comment by cprn** [comment]
I can unfortunately confirm there's an issue:
![image](https://user-images.githubusercontent.com/6132708/78959582-a9a09c80-7aeb-11ea-8d2f-5aef9258ad9c.png)

**Comment by cprn** [comment]
I can unfortunately confirm there's an issue:
![image](https://user-images.githubusercontent.com/6132708/78959627-d2289680-7aeb-11ea-8ccd-b2a69249520e.png)
