### ISSUE TITLE
[Enhancement] Change code highlight colors

### ISSUE THREAD

**Issue by GideonWolfe** [guglicap/wal-discord#24]
Discord allows you use markdown to include syntax highlighted code, like

```c
for(int i = 0; i < 10; i++){
    printf("This is highlighted");
}
```
Would it be difficult to modify the `css` to highlight code from the `wal` color pallet? 

I have done something similar in [vim.reaper](https://github.com/GideonWolfe/vim.reaper#markdown) with the markdown preview vim plugin.

**Comment by VGrol** [comment]
This is actually possible, but I'd need to get the full color palette imported from the colors file, which would require a rewrite of the backend. 

@guglicap How do you feel about this?
If we do this I'll make another pass over the current CSS and create a bit more colour variation.
Had a quick look on the colours used, more colours means better readability and it seems we're working with a palette of 6 at most.
That'd effectively mean integrating the entire colors file into the backends and just changing the order of priorities?

If you could implement the following variables in the backends we have, I can work on implementing it over the next week and seeing if I can add some variation into the existing CSS.

```scss
$colorHighlight (primary colour to compliment the accent colour)
// other than that I suppose we could just import 3 more basic colours, so a basic variable would suffice. (I don't really care for the variable names, but if you could confirm the structure I can begin writing the changes. Maybe something like this;
$colorHighlightAlt
$colourUrgentAlt
$colourAccentAlt
```

**Comment by guglicap** [comment]
Sure, have a go, I'm sure something will come of it :)

**Comment by VGrol** [comment]
Made a couple of changes to the variables, as having alt colours without using them as their main variable isn't very sensible. 

So my current draft looks like this;

```scss
@import 'colors.scss';
$bg: $background;
$bgDarker: mix($background, #000, 90%); // for sidebars and titlebars
$colorUrgent: $color6; // for new messages notifications and the alike
$colorAccent: $color1; // "encourages user interaction", I just copied from android colors
$colorHighlight: $color4; // for highlighting and complementing the accent color
$fg: $foreground; // text color

// additional colors for syntax highlight variation
$syntaxone: $color2;
$syntaxtwo: $color3;
$syntaxthree: $color5;
```

I'm not going to be touching the backends much more than this. I'll leave it up to you to swap the colours around once I finish writing my PR.
