### ISSUE TITLE
Contribute page

### ISSUE THREAD

**Issue by pixlbreaker** [guglicap/wal-discord#28]
I can add a `CONTRIBUTE.md` page for you.  It can have whatever guidelines or methods you prefer.

**Comment by guglicap** [comment]
Thank you, I appreciate the suggestion but that's actually something I'd rather do. I feel like it wouldn't make much sense to explain what I want to write down and have someone else write it down for me, hope you understand.

**Comment by pixlbreaker** [comment]
No problem! Thank you for replying and taking the time to do it!
