### ISSUE TITLE
Voice Connected frame not colored

### ISSUE THREAD

**Issue by Araly** [guglicap/wal-discord#4]
![2018-05-31-214700_1920x1080_scrot](https://user-images.githubusercontent.com/24990801/40805013-3f9c4e00-651d-11e8-80c9-a2e849085862.jpg)

I think you forgot to color this part of the interface, unless there's a problem on my part of it

**Comment by guglicap** [comment]
You're right, I forgot about it. Fixed in the latest commit. Thanks for the heads up :)
