### ISSUE TITLE
Server list and main message place now left with discord grey

### ISSUE THREAD

**Issue by Araly** [guglicap/wal-discord#5]
I think due to a discord update, first the server list on the right stopped following the wal colors, then now the main message place too, in the middle. They both have plain old discord grey. I tried looking up if I could see if they changed something but didn't end up understanding much. I'll see if I can find something on my own tinkering a bit.
![2018-08-05-152332_1920x1080_scrot](https://user-images.githubusercontent.com/24990801/43686565-506728f2-98c8-11e8-9e2c-72b134782266.png)

**Comment by guglicap** [comment]
Yeah, I'm getting it too, working on a fix right now. Should be done soon.

**Comment by Araly** [comment]
thank you, nice job, updated and works
