### ISSUE TITLE
Could not find Discord executable

### ISSUE THREAD

**Issue by Amolith** [guglicap/wal-discord#7]
I set up BeautifulDiscord using 
`sudo python3 -m pip install -U https://github.com/leovoel/BeautifulDiscord/archive/master.zip`

Then tried to run `wal-discord; beautifuldiscord --css $HOME/.cache/wal-discord/style.css` but I'm getting the error `Could not find Discord executable`. I'd be happy to provide further information if you'll tell me what you need!

**Comment by guglicap** [comment]
I think that's an issue with BeautifulDiscord and not wal-discord. 
You should probably open it in this repo: https://github.com/leovoel/BeautifulDiscord
Remember that Discord must be running in order for BeautifulDiscord to work (for the first time, at least)

**Comment by guglicap** [comment]
Closing, feel free to re-open if needed.
