### ISSUE TITLE
Friends list is default with the new Discord update (The one that introduced the gif button)

### ISSUE THREAD

**Issue by ghost** [guglicap/wal-discord#8]

**Comment by guglicap** [comment]
Alright, should be fixed in the branch [issue-#8](https://github.com/guglicap/wal-discord/tree/issue-%238) try it out and let me know. I'll merge it if you confirm it works.

**Comment by ghost** [comment]
No. I don't quite know what info I could provide to help.

**Comment by guglicap** [comment]
Post the output of `grep friend ~/.config/wal-discord/master.scss`.

**Comment by ghost** [comment]
Sorry for the late response! I completely forgot about this issue.
```
        /* n friends online */
        .friends-online, .friendsOnline-_wi_fM {
/* friends tab */
#friends {
    .friends-table {
        .friends-row:hover {
        .friends-row .friends-column-actions .friends-action {
        .friends-row .friends-column-actions .friends-action:hover {
```

**Comment by guglicap** [comment]
yeah, it looks like `~/.config/master.scss` wasn't updated, try copying `config/master.scss` there manually.

**Comment by ghost** [comment]
That's odd, it's still not working
```
[~/g/w/config]::grep friend master.scss 
        /* n friends online */
        .friends-online, .friendsOnline-_wi_fM {
/* friends tab */
#friends, .container-3gCOGc {
    .friends-table, .friendsTable-133bsv {
        .friends-row:hover, .friendsRow-2yicud:hover {
        .friends-row , .friendsRow-2yicud {
            .friends-column-actions .friends-action {
        .friends-row , .friendsRow-2yicud {
            .friends-column-actions .friends-action:hover {
[~/g/w/config]::grep friend ~/.config/wal-discord/master.scss
        /* n friends online */
        .friends-online, .friendsOnline-_wi_fM {
/* friends tab */
#friends {
    .friends-table {
        .friends-row:hover {
        .friends-row .friends-column-actions .friends-action {
        .friends-row .friends-column-actions .friends-action:hover {
```
Note: I did run `wal-discord -t` after I downloaded the new master.scss

**Comment by guglicap** [comment]
as you can see though, in the second grep, after `#friends` the `.container-3gCOGc` part is missing, I don't know why, since you should have copied it manually. You can try, alternatively, `ln -sf ~/g/w/config/master.scss ~/.config/wal-discord/master.scss` which also has the benefit of keeping wal-discord updated by just running `git pull` in the repo.

**Comment by ghost** [comment]
I'm an idiot, I thought I only had to update the master.scss in the cloned directory, not in my .config. Sorry man, the issue-8 branch works perfectly.
